server:
  port: 8022


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mysql://127.0.0.1:3306/dubbo-order?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false


mybatis:
  mapper-locations: classpath*:mapper/*.xml
#指定当前服务/应用的名字（同样的服务名字相同，不要和别的服务同名）
dubbo:
  application:
    name: order-service
  protocol:
    name: dubbo
    prot: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  provider:
    timeout: 1000