server:
  port: 8023

#重试次数
curator:
  retryCount: 5
  #重试间隔时间
  elapsedTimeMs: 5000
  # zookeeper 地址
  connectString: 127.0.0.1:2181
  # session超时时间
  sessionTimeoutMs: 60000
  connectionTimeoutMs: 5000


spring:
  application:
    name: dubbo-sample-web

  # redis config
  redis:
    port: 6379
    host: 127.0.0.1
kafka:
  host:
    name: localhost:9092
  topic:
    name: logger-channel
logging:
  config: classpath:logback-spring.xml


dubbo:
  application:
    name: web-admin
  registry:
    address: zookeeper://127.0.0.1:2181
